// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_bridge_state`, `gf256_inv`, `gf256_mul`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeState`

String initBridge({required List<int> strongboxSeed}) =>
    RustLib.instance.api.crateApiInitBridge(strongboxSeed: strongboxSeed);

Uint8List getEntropyWithSeed() =>
    RustLib.instance.api.crateApiGetEntropyWithSeed();

Uint8List generateBbsProof(
        {required List<int> dpkBytes,
        required List<int> sigBytes,
        required List<String> messages,
        required Uint64List revealedIndices}) =>
    RustLib.instance.api.crateApiGenerateBbsProof(
        dpkBytes: dpkBytes,
        sigBytes: sigBytes,
        messages: messages,
        revealedIndices: revealedIndices);

List<Uint8List> splitSecretApi(
        {required List<int> secret,
        required int threshold,
        required int total}) =>
    RustLib.instance.api.crateApiSplitSecretApi(
        secret: secret, threshold: threshold, total: total);

Uint8List reconstructSecretApi({required List<Uint8List> shares}) =>
    RustLib.instance.api.crateApiReconstructSecretApi(shares: shares);

Uint8List encodeMdocBytes(
        {required List<int> docType, required List<int> dataJson}) =>
    RustLib.instance.api
        .crateApiEncodeMdocBytes(docType: docType, dataJson: dataJson);

Uint8List signMsoBytes(
        {required List<int> msoBytes, required List<int> issuerPrivateKey}) =>
    RustLib.instance.api.crateApiSignMsoBytes(
        msoBytes: msoBytes, issuerPrivateKey: issuerPrivateKey);

bool verifyProofApi(
        {required List<int> publicKey,
        required List<int> proof,
        required BigInt totalMessageCount,
        required List<int> revealedIndices,
        required List<Uint8List> revealedMessagesContent,
        required List<int> nonce,
        required BigInt aliasIndex,
        Uint8List? freshnessClaim}) =>
    RustLib.instance.api.crateApiVerifyProofApi(
        publicKey: publicKey,
        proof: proof,
        totalMessageCount: totalMessageCount,
        revealedIndices: revealedIndices,
        revealedMessagesContent: revealedMessagesContent,
        nonce: nonce,
        aliasIndex: aliasIndex,
        freshnessClaim: freshnessClaim);
